# Data Shapes

In [1]:
import numpy as np

### One Dimensional Data

In [3]:
data = np.random.rand(3)
print (data)

[0.59860173 0.48392011 0.16471542]


### Two Dimensional Data

In [6]:
data= np.random.rand(5,4)
print(data)

[[0.64569645 0.75555195 0.35571464 0.45934937]
 [0.72762856 0.1143941  0.89474045 0.75746258]
 [0.46739374 0.29439026 0.07119033 0.25381843]
 [0.09426513 0.91867279 0.12923449 0.61564521]
 [0.1878441  0.91411756 0.15011864 0.45207843]]


### Three Dimensional Data

In [8]:
data= np.random.rand(5,4,3)
print(data)

[[[0.6094238  0.61916104 0.73197441]
  [0.05432779 0.23004026 0.59567705]
  [0.24937186 0.73344775 0.64303143]
  [0.3580983  0.92721339 0.97865907]]

 [[0.25457888 0.34281805 0.42226803]
  [0.6888323  0.82901484 0.7711393 ]
  [0.96654598 0.09523455 0.01687828]
  [0.508999   0.19680078 0.7852374 ]]

 [[0.28914236 0.131602   0.15130114]
  [0.07760525 0.62601025 0.44499254]
  [0.14789248 0.11812068 0.09947714]
  [0.23570624 0.95492378 0.81506127]]

 [[0.49599566 0.45725591 0.16948116]
  [0.24410634 0.75582474 0.58607287]
  [0.40595834 0.18605637 0.46159471]
  [0.94215911 0.35092078 0.3324356 ]]

 [[0.32755615 0.94254788 0.27884392]
  [0.67772563 0.64571816 0.92436475]
  [0.92958719 0.5082325  0.62921943]
  [0.82457937 0.68787812 0.44638721]]]


### Four Dimensional Data

In [10]:
data= np.random.rand(5,4,3,2)
print(data)

[[[[0.81917932 0.26259345]
   [0.13508754 0.08536477]
   [0.24413789 0.17524298]]

  [[0.52074898 0.49033576]
   [0.5435958  0.56524634]
   [0.33406813 0.10379148]]

  [[0.39963938 0.75010969]
   [0.64226326 0.09764605]
   [0.70156419 0.13331939]]

  [[0.28628524 0.20640914]
   [0.52812086 0.75649825]
   [0.65902418 0.61495798]]]


 [[[0.71470107 0.15108509]
   [0.95004436 0.59917074]
   [0.03941379 0.49027716]]

  [[0.98667778 0.0917125 ]
   [0.92989461 0.52914075]
   [0.38739364 0.07427528]]

  [[0.08637345 0.94698163]
   [0.76122728 0.74704055]
   [0.30946516 0.0714948 ]]

  [[0.93079431 0.58595873]
   [0.12404169 0.94588612]
   [0.6459328  0.58518023]]]


 [[[0.08591306 0.93791444]
   [0.96377467 0.87647462]
   [0.56017111 0.18764972]]

  [[0.7549077  0.81577415]
   [0.45478035 0.81325523]
   [0.61397245 0.79609428]]

  [[0.67107888 0.30187026]
   [0.90994125 0.23403582]
   [0.93991151 0.08276737]]

  [[0.64968363 0.66614204]
   [0.51981061 0.837622  ]
   [0.79799941 0.23453789]]]


## Data Reshaping 

### One Dimensional Data to Single Column Matrix

In [11]:
data= np.random.rand(10)
print(data)

[0.44500941 0.14987728 0.40311068 0.63754959 0.71087436 0.95400685
 0.41961986 0.69708653 0.17763809 0.87002816]


In [12]:
data.reshape(10,1)

array([[0.44500941],
       [0.14987728],
       [0.40311068],
       [0.63754959],
       [0.71087436],
       [0.95400685],
       [0.41961986],
       [0.69708653],
       [0.17763809],
       [0.87002816]])

### One Dimensional Data to Multiple Column Matrix

In [14]:
data.reshape(5,2)

array([[0.44500941, 0.14987728],
       [0.40311068, 0.63754959],
       [0.71087436, 0.95400685],
       [0.41961986, 0.69708653],
       [0.17763809, 0.87002816]])

### Check the Shape of our Data

In [15]:
print(data.shape)

(10,)
